### ISSUE TITLE
Time out/delayed events

### ISSUE THREAD

**Issue by guizmo01** [dubit/unity-http#11]
Would be nice if could be able to handle time out events

**Comment by borntocompile** [comment]
Hi guizmo01,

Currently the Http system does not ship with functionality to delay an event.
Alternatively, we have a repository for Unity utilities here: https://github.com/dubit/duck-utils
Inside this module is a Timer class: https://github.com/dubit/duck-utils/blob/development/Docs/Timer.md

This Timer system combined with the Http system allows you to do something like:
```
Timer.SetTimeout(duration: 10, () => {
    Http.Get("http://127.0.0.1:8080/")
        .OnSuccess(response => Debug.Log(response.StatusCode))
        .OnError(response => Debug.Log(response.StatusCode))
        .OnNetworkError(response => Debug.Log(response.StatusCode))
        .Send();
});
```
This will wait 10 seconds and then run the method.

Similarly for time outs:
```
var request = Http.Get("http://127.0.0.1:8080/")
    .OnSuccess(response => Debug.Log(response.StatusCode))
    .OnError(response => Debug.Log(response.StatusCode))
    .OnNetworkError(response => Debug.Log(response.StatusCode))
    .Send();

Timer.SetTimeout(duration: 10, () => {
    request.Abort();
}):
```
After 10 seconds the request will abort.

-----------------------------

However, if you are referring to request network timeouts then:

`OnNetworkError` will be invoked if the timeout is due to a system error. There are no response codes for a network error as the request never makes it to a server.
`OnError` will be invoked if the server responds with an error, the server will handle which code it responds with. 

A list of common response codes can be found here: https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

To check the response code of a request, see example below:
```
Http.Get("http://127.0.0.1:8080/")
    .OnSuccess(response => Debug.Log(response.StatusCode))
    .OnError(response => Debug.Log(response.StatusCode))
    .OnNetworkError(response => Debug.Log(response.StatusCode))
    .Send();
```

**Comment by guizmo01** [comment]
Nice, Thank you.

I think unity webrequest has a timeout.

https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest-timeout.html

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by borntocompile** [comment]
Hi guizmo01, 

Thank you for the useful information. 
You can find the method `SetTimeout(int duration)` inside `HttpRequest` in the[ latest version 2.1.0](https://github.com/dubit/unity-http/releases)

Heres an example use:

```
Http.Get("http://127.0.0.1:4000/")
	.SetTimeout(duration: 30)
	.OnSuccess(response => Debug.Log(response.StatusCode))
	.OnError(response => Debug.Log(response.StatusCode))
	.OnNetworkError(response => Debug.Log(response.StatusCode))
	.Send();
```

Thanks,
Harry
